organizations:
    path:      /api/organizations
    defaults:  { _controller: AppBundle:Default:organizations}
    methods: [GET]

frontend:
    path:      /{path}
    defaults:  { _controller: AppBundle:Default:frontend, path: '' }
    requirements:
        path: .+